/* Board Action */
export const BOARD_REQUEST_CONTACTS = "BOARD_REQUEST_CONTACTS";
export const BOARD_RECEIVED_CONTACTS = "BOARD_RECEIVED_CONTACTS";
export const BOARD_SELECT_CONTACT = "BOARD_SELECT_CONTACT";
export const BOARD_REQUEST_FAIL = "BOARD_REQUEST_FAIL";